backend:
  name: github
  repo: 4460lab/blog
  branch: main
  auth_endpoint: /api/auth/callback

media_folder: public/images
public_folder: /images

collections:
  - name: "posts"
    label: "記事"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "発行日", name: "date", widget: "datetime" }
      - { label: "概要", name: "excerpt", widget: "text", required: false }
      - { label: "本文", name: "body", widget: "markdown" }
